var GLOBAL_POWERUP_CHANCE = 0.15;

var DEFAULT_WEIGHTS = [
	/* Acid */                  8,
	/* AntiGravity */          20,
	/* Assist */                8,
	/* Attract */               8,
	/* Autopilot */             4,
	/* Ball Cannon */           2,
	/* Barrier */               8,
	/* Blackout */              8,
	/* Beam */                 20,
	/* Blossom */               4,
	/* Bomber */                2,
	/* Bulk */                  4,
	/* Bypass */                2,
	/* Cannon */                8,
	/* Catch */                80,
	/* Change */               40,
	/* Chaos */                 8,
	/* Column Bomber */         4,
	/* Combo */                40,
	/* Control */               4,
	/* Disarm */                8,
	/* Disrupt */               4,
	/* Domino */               40,
	/* Drill Missile */         2,
	/* Drop */                  8,
	/* EMP Ball */             20,
	/* Energy */               20,
	/* Erratic Missile */       8,
	/* Extend */               80,
	/* Fast */                 80,
	/* Freeze */                8,
	/* Fireball */              8,
	/* Forcefield */            8,
	/* Frenzy */                1,
	/* Gelato */               20,
	/* Generator Ball */        4,
	/* Ghost */                 8,
	/* Giga */                  1,
	/* Glue */                 40,
	/* Gravity */               4,
	/* Hold Once */            40,
	/* Hacker */                4,
	/* Halo */                  4,
	/* HaHa */                 20,
	/* Heaven */               40,
	/* Ice Ball */             20,
	/* Illusion */             40,
	/* Indigestion */           8,
	/* Intelligent Shadow */    4,
	/* Invert */               40,
	/* Irritate */             20,
	/* Javelin */               4,
	/* Junk */                 20,
	/* Jewel */                20,
	/* Joker */                 8,
	/* Kamikaze */              1,
	/* Knocker */              40,
	/* Laceration */            2,
	/* Large Ball */           20,
	/* Laser */                40,
	/* Laser Plus */            8,
	/* Laser Ball */           40,
	/* Lock */                 40,
	/* Luck */                  2,
	/* Magnet */                4,
	/* Mega */                  4,
	/* Missile */               4,
	/* Mobility */              8,
	/* Multiple */             40,
	/* Mystery */               8,
	/* Nano */                  1,
	/* Nebula */                4,
	/* New Ball */             40,
	/* Node */                 20,
	/* Normal Ball */          20,
	/* Normal Ship */          20,
	/* Nervous */               8,
	/* Oldie */                 1,
	/* Open */                  8,
	/* Orbit */                40,
	/* Particle */             40,
	/* Pause */                20,
	/* Player */                2,
	/* Probe */                 8,
	/* Poison */                2,
	/* Protect */              40,
	/* Quake */                 4,
	/* Quasar */                2,
	/* Quadruple */             8,
	/* Rapidfire */            20,
	/* Restrict */             80,
	/* Regenerate */           20,
	/* Re-Serve */             40,
	/* Reset */                 4,
	/* Risky Mystery */         8,
	/* Rocket */                2,
	/* Row Bomber */            8,
	/* Shrink */               10,
	/* Shadow */                8,
	/* Shotgun */               4,
	/* Sight Laser */          20,
	/* Slow */                 80,
	/* Snapper */               4,
	/* Slug */                  8,
	/* Terraform */             2,
	/* Time Warp */             4,
	/* Trail */                 8,
	/* Tractor */              20,
	/* Transform */             8,
	/* Triple */               40,
	/* Twin */                 20,
	/* Two */                  40,
	/* Ultraviolet */           8,
	/* Unification */           1,
	/* Undead */               20,
	/* Unlock */                4,
	/* Undestructible */        4,
	/* Vendetta */             20,
	/* Vector */                4,
	/* Venom */                 4,
	/* Volt */                 40,
	/* Voodoo */               20,
	/* Warp */                  1,
	/* Weak */                 20,
	/* Weight */                8,
	/* Wet Storm */             4,
	/* Whisky */                8,
	/* X-Bomb */                2,
	/* X-Ray */                 2,
	/* Yoyo */                  8,
	/* Yoga */                  8,
	/* Y-Return */              8,
	/* Buzzer */                4,
	/* Zeal */                  8,
	/* Zen Shove */            20,
];